import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Snowfall/Floating Lights Animation */}
        <div className="snowfall">
          <div className="snow-dot"></div>
          <div className="snow-dot"></div>
          <div className="snow-dot"></div>
          <div className="snow-dot"></div>
          <div className="snow-dot"></div>
          <div className="snow-dot"></div>
          <div className="snow-dot"></div>
          <div className="snow-dot"></div>
          <div className="snow-dot"></div>
          <div className="snow-dot"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
